# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci_renesas" "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9301-67DB";
    fsType = "vfat";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/156a8c59-1fa3-46ca-9846-da89acaf1761";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd:3" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/156a8c59-1fa3-46ca-9846-da89acaf1761";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/eff07676-e9ac-46e2-83cf-454e0b88a088";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/156a8c59-1fa3-46ca-9846-da89acaf1761";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd:3" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/156a8c59-1fa3-46ca-9846-da89acaf1761";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd:3" "noatime" ];
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
